name: CI/CD Docker Build and ArgoCD Sync

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 454563073530.dkr.ecr.us-east-1.amazonaws.com
  IMAGE_REPO: hello-world

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build Docker image
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE_REPO:${{ github.run_number }} .
          docker tag $ECR_REGISTRY/$IMAGE_REPO:${{ github.run_number }} $ECR_REGISTRY/$IMAGE_REPO:latest

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REGISTRY/$IMAGE_REPO:${{ github.run_number }}
          docker push $ECR_REGISTRY/$IMAGE_REPO:latest

      - name: Update Helm values.yaml with new image tag
        run: |
          sed -i "s/tag: .*/tag: $GITHUB_RUN_NUMBER/" helm/values.yaml
          git config user.email "ci-bot@yourdomain.com"
          git config user.name "CI Bot"
          git add helm/values.yaml
          git commit -m "Update image tag to $GITHUB_RUN_NUMBER [skip ci]" || echo "No changes to commit"
          git push https://${{ secrets.GIT_PAT }}@github.com/${{ github.repository }}.git HEAD:main
